import {
    Given,
    When,
    Then,
  } from "@badeball/cypress-cucumber-preprocessor";
  import { assetsPage } from '@pages/AssetsPage';
  
  
  Then("Click create assets button.", () => {
    cy.wait(3000);
    assetsPage.createassets().click();
   
  })
  
  Then("Verify that the User able to see the Add new Asset  Pop-Up screen.", () => {
   
    //cy.get('.popup-selector').should('be.visible');
    //assetsPage.popupheadname().should('exist');
    console.log('The Pop-up screen is displayed');
  })
  
  Then("Click Upload photo button and choose files format JPEG,PNG,GIF.", () => {
   
  })
  
  Then("Verify when User able to Upload photo for New Asset.", () => {
   
  })
  
  Then(" Verify that the User able to view the Autogenerated Asset ID and ensure the ID value are combined both AlphaNumeric.", () => {
   
  })
  
  Then("Verify the User see list of fields in Add new asset Pop-Up screen.", () => {
    cy.wait(3000);
    assetsPage.popupassetnametitle().should('be.visible');
    assetsPage.popuppurchasetitle().should('be.visible');
    assetsPage.popupguarentytitle().should('be.visible');
    assetsPage.popuporganisationtitle().should('be.visible');
    assetsPage.popupdepartmenttitle().should('be.visible');
    assetsPage.popuplaboratorytitle().should('be.visible');
    assetsPage.popupstatustitle().should('be.visible');
    assetsPage.popupavailabilitytitle().should('be.visible');
  })
  Then("Click Cancel From Add new Asset Pop-Up screen.", () => {
    assetsPage.popupcancel().click();
    cy.wait(2000);
  })
  Then("Click Yes from Confirmation screen.", () => {
   
    assetsPage.confirmyes().click();
  })
  Then("Ensure it Redirect to Asset Page after click Yes.", () => {
    console.log('The Page redirects to assets page after clicked yes');
  })
  Then("Click No from Confirmation screen.", () => {
    assetsPage.confirmno().click();
  })
  Then("Ensure it Redirect to Asset Page after click No.", () => {
    console.log('The Page redirects to assets page after clicked No');
  })
  Then("Click Enter Asset Name Textbox and  enter name with allowed character 8-16 without Numeric.", () => {
    assetsPage.popupassetsname().type('Voltmeter');
  })
  Then("Click Calender icon in Purchase date field and choose date wisely.", () => {
    cy.wait(1000);
    assetsPage.popuppurchasedate().click();
    cy.wait(1000);
    assetsPage.purchasedatechoose().click();

  })
  Then("Verify that the User able to choose the Purchased Date based on Asset.", () => {
    console.log('Able to choose purchase date on assets');
  })
  Then("Click Calender icon in Guaranty Warranty Expiry date field and choose date wisely.", () => {
    cy.wait(1000);
    assetsPage.popupguarantydate().click();
    cy.wait(1000);
    assetsPage.purchasedatechoose().click();
  })
  Then("Verify that the User able to choose the Guaranty Warranty Expiry Date based on Asset.", () => {
    console.log('Able to choose Guaranty date on assets');
  })
  Then("Click Organisation Dropdown and Select wisely.", () => {
    assetsPage.assetsdepartmentdropdown().click();
  })
  Then("Click Department Dropdown and Select wisely.", () => {
    assetsPage.popupdepartment().click();
    cy.wait(1000);
    assetsPage.popupdepartmentoptions().click();
    cy.wait(1000);
  })
  Then("Click Labaratory Dropdown and Select wisely.", () => {
    assetsPage.popuplaboratory().click();
    cy.wait(1000);
    assetsPage.popuplaboratoryoptions().click();
    cy.wait(1000);
  })
  Then("Click Status Dropdown and Select wisely.", () => {
    assetsPage.popupstatus().click();
    cy.wait(1000);
    assetsPage.statusinactive().click();
    cy.wait(1000);
  })
  Then("Click Availability Dropdown and Select wisely.", () => {
    assetsPage.popupavailability().click();
    cy.wait(1000);
    assetsPage.availablestatus().click();
  })
  Then("Click Create button.", () => {
   assetsPage.popupcreate().click();
  })